### PR TITLE
switch BGM.

### PR DESCRIPTION
**Pull request by ryota8bit**
BGM: music(0) --> music(25), music(15) --> music(33)

**Proposal**
@ayalan @avcdsld 
What do you think about the following?
* Play music(19) before music(33) is played.
* music(0) is played on the game over screen

### CODE REVIEW

**Comment by ayalan** [comment]
There seems to be some weird effect to the BGM when a match is made (causing SFX to be used); it seems like the music is skipping to a different part of the song?

**Comment by ayalan** [comment]
I think it's related to this:

> A call to music() can include a channel mask to declare which sound channels should not be interrupted by a sound effect played by a call to [sfx()](https://pico-8.fandom.com/wiki/Sfx). The channel mask is a bitfield, where channels 0, 1, 2, and 3 are represented by the corresponding bits, with values 1, 2, 4, and 8, respectively. A call to [sfx()](https://pico-8.fandom.com/wiki/Sfx) may still take over a channel reserved by the music pattern if it specifies an explicit channel number.

>
>When using music and sound effects together, it is a good idea to set a channel mask that reserves some channels and leaves others open for effects. PICO-8 will prioritize the use of the unmasked channels for sound effects, giving both music and sound a chance to play.

From https://pico-8.fandom.com/wiki/Music

Basically, when the music is playing, it's probably using all 4 channels. When the SFX plays, it uses some channels. We need to declare which channels should not be interrupted. I think whichever channel carries the melody should have this applied. Let's talk about it in our next meeting.

**Comment by avcdsld** [comment]
Fixed the function to clear vertical and horizontal at the same time. This is a rather large modification, so I would appreciate it if you could check to see if there are any problems.

**Comment by ayalan** [comment]
@KoganezawaRyouta Can we reduce the volume of all tracks, so it's about 25~50%? I think the volume seems quite high in comparison to other games on Splore. https://github.com/avcdsld/pepe-crush/issues/35

@avcdsld I confirmed that the horizontal / vertical clear appears to work in the scenarios I encountered.

@KoganezawaRyouta @avcdsld I noticed something strange when the bomb is used. 
(1) When bomb is used, the bomb SFX is triggered, but I have a feeling this might be the wrong sound? 
(2) After the current bomb SFX is triggered, the baseline channel of the BGM no longer plays.
I have a recording of problem (2) in the video.
https://github.com/avcdsld/pepe-crush/issues/36

Scenario 1:
There is a brush bomb. The brush bomb is matched with 3 and the base line of the music stops.
https://user-images.githubusercontent.com/1248159/191635182-99deedb3-8c7e-4d4a-84ae-91e3bbc7efe1.mp4

Scenario 2:
The baseline of the music has already stopped due to scenario 1.
When a bomb is used again (collagen drop bomb), the bomb sfx (which seems to be the same as the missing baseline?) plays and then stops again.
https://user-images.githubusercontent.com/1248159/191635396-a0b4bb71-3cd3-43aa-81a8-a88560ec014a.mp4

**Comment by ayalan** [comment]
One more missing thing:
we should have the music 0 used on Game Over screen after the game over sfx plays. 
https://github.com/avcdsld/pepe-crush/issues/37

**Comment by ayalan** [comment]
Confirming that the music / sfx bug appears to be fixed.

**Comment by ayalan** [comment]
I confirmed that the music now plays at game over / share screens.

**Pull request merged**
